create table student(id int primary key, name varchar(20))
create table token_t(token varchar(100) primary key, is_active varchar(1))
insert into student values(1, 'Peter')
insert into student values(2, 'Jack')
insert into student values(3, 'Lucy')
